name: 'GbG app: delpoy to Netlify on "push" to "main" and PRs'

on:
  push:
    branches:
      - main
    paths:
      - 'apps/grainbygrain/**'
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'apps/grainbygrain/**'
  workflow_dispatch:

env:
  VITE_GBG_NHOST_SUBDOMAIN: ${{ secrets.VITE_GBG_NHOST_SUBDOMAIN }}
  VITE_GBG_NHOST_REGION: ${{ secrets.VITE_GBG_NHOST_REGION }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  delpoy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Grain by Grain App and all the dependant libraries
        run: pnpm turbo run build -F grain-by-grain

      - name: Prod Deploy to Netlify
        if: ${{ github.ref_name == 'main' }}
        run: |
          netlify deploy \
            --dir './apps/grainbygrain/dist' \
            --filter grain-by-grain \
            --message "${{ github.event.pull_request.title }}" \
            --prod \
            --site ${{ secrets.NETLIFY_GBG_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \

      - name: Preview Deploy to Netlify
        if: ${{ github.ref_name != 'main' }}
        id: preview_deploy
        run: |
          netlify deploy \
            --dir './apps/grainbygrain/dist' \
            --filter grain-by-grain \
            --message "${{ github.event.pull_request.title }}" \
            --alias deploy-preview-${{ github.event.pull_request.number }} \
            --site ${{ secrets.NETLIFY_GBG_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \

      - name: Post Deployment Comment
        if: ${{ github.ref_name != 'main' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: deployment-preview
          message: |
            ### ✅ Deployment Preview Ready

            | Environment | URL |
            |-------------|-----|
            | <span aria-hidden="true">🔨</span> Latest commit | ${{ github.event.pull_request.head.sha }} |
            | Preview     | https://deploy-preview-${{ github.event.pull_request.number }}--grainbygrain.netlify.app |
